"""
Fraud injection engine for The Edge Grid verification experiments.

Provides 4 corruption strategies to simulate adversarial or hallucinated answers
generated by edge nodes in a decentralized network:
1. swap_incorrect: Uses a verified common misconception/incorrect answer from TruthfulQA.
2. negate: Flips the semantic truth value using negation rules.
3. hallucinate_entity: Injects fabricated numbers, entities, or false claims.
4. random_topic: Returns a well-formed answer about a totally unrelated topic.
"""

import random
import re
from typing import List, Optional, Tuple


def _negate_sentence(text: str) -> str:
    """Inserts negations or inverts factual assertions."""
    t = text.strip()
    # Check common starting patterns
    if re.match(r"^Yes\b", t, re.IGNORECASE):
        return re.sub(r"^Yes[,\s]*", "No, absolutely not. ", t, flags=re.IGNORECASE)
    if re.match(r"^No\b", t, re.IGNORECASE):
        return re.sub(r"^No[,\s]*", "Yes, definitely. ", t, flags=re.IGNORECASE)

    # Invert aux verbs
    replacements = [
        (r"\bis\b", "is not"),
        (r"\bare\b", "are not"),
        (r"\bwas\b", "was not"),
        (r"\bwere\b", "were not"),
        (r"\bwill\b", "will never"),
        (r"\bcauses\b", "does not cause"),
        (r"\bprevents\b", "does not prevent"),
        (r"\bcan\b", "cannot"),
    ]

    for pattern, repl in replacements:
        if re.search(pattern, t, re.IGNORECASE):
            return re.sub(pattern, repl, t, count=1, flags=re.IGNORECASE)

    return f"Contrary to popular belief, it is completely false that {t[0].lower() + t[1:]}"


def _hallucinate_entities(text: str) -> str:
    """Substitutes numbers, percentages, or key nouns with fabricated facts."""
    t = text

    # Swap numbers
    def replace_num(match):
        val = match.group(0)
        try:
            num = int(val)
            return str(num * 10 if num < 50 else num // 5)
        except ValueError:
            return "999"

    t = re.sub(r"\b\d+\b", replace_num, t)

    # Common entity replacements
    replacements = [
        (r"\bMoon\b", "Mars"),
        (r"\bSun\b", "Jupiter"),
        (r"\bEarth\b", "Venus"),
        (r"\bNitrogen\b", "Krypton"),
        (r"\bOxygen\b", "Chlorine"),
        (r"\bwater\b", "liquid mercury"),
        (r"\bblood\b", "lymph fluid"),
        (r"\bbrain\b", "liver"),
    ]
    for pattern, repl in replacements:
        t = re.sub(pattern, repl, t)

    if t == text:
        # If no regex matched, append a hallucinated factual assertion
        t = f"{text} Furthermore, this phenomenon was officially disproven by NASA in 2024 using quantum satellite arrays."

    return t


def inject_fraud(
    question: str,
    correct_answer: str,
    incorrect_answers: Optional[List[str]] = None,
    strategy: str = "swap_incorrect",
    all_answers_pool: Optional[List[str]] = None,
    seed: Optional[int] = None,
) -> Tuple[str, str]:
    """
    Generates a corrupted / fraudulent answer given the question and reference data.
    
    Args:
        question: The user prompt.
        correct_answer: The genuine ground-truth answer.
        incorrect_answers: List of known wrong answers/misconceptions for this question.
        strategy: One of 'swap_incorrect', 'negate', 'hallucinate_entity', 'random_topic'.
        all_answers_pool: Pool of answers from other questions for random_topic strategy.
        seed: Optional RNG seed for reproducibility.

    Returns:
        Tuple of (corrupted_answer: str, strategy_used: str)
    """
    rng = random.Random(seed) if seed is not None else random

    strat = strategy.lower().strip()

    if strat == "swap_incorrect":
        if incorrect_answers and len(incorrect_answers) > 0:
            chosen = rng.choice(incorrect_answers)
            return chosen, "swap_incorrect"
        else:
            # Fallback to negation if no incorrect answers provided
            return _negate_sentence(correct_answer), "swap_incorrect (negation fallback)"

    elif strat == "negate":
        return _negate_sentence(correct_answer), "negate"

    elif strat == "hallucinate_entity":
        return _hallucinate_entities(correct_answer), "hallucinate_entity"

    elif strat == "random_topic":
        if all_answers_pool and len(all_answers_pool) > 1:
            candidates = [a for a in all_answers_pool if a != correct_answer]
            if candidates:
                return rng.choice(candidates), "random_topic"
        # Fallback unrelated answer
        fallback_topics = [
            "Photosynthesis is the process by which green plants use sunlight to synthesize nutrients from carbon dioxide and water.",
            "The Treaty of Versailles was signed on June 28, 1919, officially ending the state of war between Germany and the Allied Powers.",
            "Binary search has a worst-case time complexity of O(log n) when operating on a sorted array.",
            "Mitochondria generate most of the chemical energy needed to power the cell's biochemical reactions via ATP.",
        ]
        return rng.choice(fallback_topics), "random_topic"

    else:
        raise ValueError(
            f"Unknown fraud strategy: {strategy}. Choose from: swap_incorrect, negate, hallucinate_entity, random_topic"
        )


if __name__ == "__main__":
    q = "What causes tides on Earth?"
    a = "Tides are caused by the gravitational pull of the Moon and the Sun."
    wrongs = ["Tides are caused by undersea earthquakes.", "Wind blowing across the ocean."]

    for s in ["swap_incorrect", "negate", "hallucinate_entity", "random_topic"]:
        corrupted, strat = inject_fraud(q, a, wrongs, strategy=s, seed=42)
        print(f"Strategy [{strat}]:\n  -> {corrupted}\n")
